---
title: "Blog 1_Module 1: Dichotmous thinking in cognitive psychology"
description: |
  Welcome to our new blog, My Blog. We hope you enjoy 
  reading what we have to say!
author:
  - name: Ellie Grossman
    url: 
    affiliation: CUNY Graduate Center
    affiliation_url: https://www.gc.cuny.edu/Home
date: 08-31-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```

After my first foray into cognitive psychology literature, I am feeling like a neophyte. Aside from the domain lexicon that I have not yet acquired, the richness of philosophy and metanalysis was unexpected and will admittedly take longer than the scope of this assignment to parse through. That said, the thread of reflexivity (that I am happy to see extends back to the early 20th century!) that was demonstrated across each of these three readings is the one I will tug as I reckon with these notions of conceptualizing perception and the field of cognitive psychology at large.
Like Allen Newell, I too am distressed with the patterns that I see within my field of developmental psychology. We developmental researchers spin our wheels attempting to dissect, reattach, and at times, mangle, the phenomena we examine (a quick dive into eugenic research grounded in evolution-based theory should be sufficient) through a series of peer-accepted scientific experiments, in which “those phenomena form a veritable horn of plenty for our experimental life, the spiral of the horn itself growing all the while it pours forth the requirements for secondary experiments” (p. 4; Newell, 1973). While there is much creativity and freedom in asking questions to elicit more questioning, Newell begs the query of whether we are truly serving our goals to understand phenomena [in the case of these articles, perception, memory and attention] or whether we are serving the goals of scientific convention. Going on to critique the low hanging fruit of false dichotomies, or binary oppositions, that researchers strive for to justify observations of nature, Newell oddly suggests that research questions would benefit from dichotomous reasoning, in order to “not risk much” with the beneficial caveat being that this births a scientific inquiry rife with possibility for subsequent experimental attack (p. 8). 
In my experience, binary oppositions are rarely reflected back in nature, no matter how cleanly they map onto dichotomous constructs designed in the laboratory. According to Schacter, Eich, and Tulving’s interpretation of Semon’s theory of engrams, or physical substrates of memory from the brain, he was quite adamant that these engrams are stored through physiochemical processes in the brain (1978). In Newellian prose, Semon’s experiments poured forth requirements for secondary experiments in his dichotomous questioning of whether memory storage is a localized or distributed process. Future decades of research has gone on to examine this 1920s-era question. While a cursory look on Google Scholar tells me that we now lean towards the notion of localized memory storage, a 1991 work by Richard F. Thompson aptly entitled “Are memory traces localized or distributed?” may shed light that these questions have yet to be answered. A further look into the literature exposes many an article on the mechanisms of distributed memory storage, from in-memory computing architectures of distributed memory (Kang & Shanbhag, 2016) to notions about the distributed nature of memory itself (Christophel, Klink, Spitzer, Roelfsema, & Haynes, 2017). What does this tell us? I certainly do not advocate for the eradication of or-based questioning, though seeking – nay, hoping for? – dichotomy may be a futile endeavor. 
Perhaps a more concrete example of futile dichotomous thinking than my Google searches is the 1956 work of George Miller in his writing of variance in information processing. Then-contemporary findings suggested that “no matter how many alternative tones we ask [the participant] to judge, the best we can expect them to do is to assign them to about six different classes without error” (p. 64, Miller; 1956). Miller goes on to discuss the surprise (and disappointment?) that this number is as small as six. Beyond layperson assumption, he describes that this fulcrum-atic reasoning between memory and accuracy led psychologists to long use seven-point scales to quantify information processing, “on the intuitive basis that trying to rate into finer categories does not really add much to the usefulness of ratings” (p. 84). This logic is interrupted, however, when the notion of capacity is introduced into this model, the phenomena becomes less reproducible across subdomains. For example, in Eriksen’s investigation of multi-dimensional stimuli, he finds that when more variables are added to the display, one’s total capacity is increased, why accuracy is decreased. In other words, we can make relatively crude judgments of several things simultaneously. According to Miller’s theory, this increased capacity in a “fluctuating world” may provide an evolutionary theory for human’s ultimate survival; and yet, accuracy is still most often used for contemporary measures of aptitude (Winke, 2017).
False dichotomies, and the assumption that dichotomous questioning is always advantageous, is admittedly a highly saturated area within Developmental Psychology (e.g., the ole’ nature vs. nurture debate), and one that I am steeped in within my Department. I do hope that I am able to grow my ability to perspective shift to a cognition-based lens over the course of the semester. I look forward to examining and critiquing these long-standing dichotomous debates within cognition in this class with the hope of a porous outlook with which to identify constructs.

References Cited

Christophel, T. B., Klink, P. C., Spitzer, B., Roelfsema, P. R., & Haynes, J. D. (2017). The distributed nature of working memory. Trends in cognitive sciences, 21(2), 111-124.

Kang, M., & Shanbhag, N. R. (2016). In-memory computing architectures for sparse distributed memory. IEEE transactions on biomedical circuits and systems, 10(4), 855-863.

Miller, G. A. (1956). The magical number seven, plus or minus two: Some limits on our capacity for processing information. Psychological Review, 63(2), 81.

Newell, A. (1973). YOU CAN’T PLAY 20 QUESTIONS WITH NATURE AND WIN: PROJECTIVE COMMENTS ON THE PAPERS OF THIS SYMPOSIUM. In Visual Information Processing (pp. 283–308). Elsevier. https://linkinghub.elsevier.com/retrieve/pii/B9780121701505500123

Schacter, D. L., Eich, J. E., & Tulving, E. (1978). Richard Semon’s theory of memory. Journal of Verbal Learning and Verbal Behavior, 17(6), 721–743. https://doi.org/10/bqwd4r

Thompson, R. F. (1991). Are memory traces localized or distributed?. Neuropsychologia, 29(6), 571-582.

Winke, P. M. (2018). Aptitude Testing. The TESOL Encyclopedia of English Language Teaching, 1-7.



